plugins:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "bin/**/*"
    - "db/schema.rb"
    - "db/queue_schema.rb"
    - "node_modules/**/*"
    - "vendor/**/*"
    - "tmp/**/*"
    - "log/**/*"

Rails/BulkChangeTable:
  Exclude:
    - "db/migrate/**/*"

Rails/SkipsModelValidations:
  Exclude:
    - "app/services/importers/**/*"

RSpec/MultipleExpectations:
  Max: 12
  Exclude:
    - "spec/services/importers/xml/*_importer_spec.rb"
    - "spec/services/importers/importer_factory_xml_spec.rb"

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "db/migrate/**/*"
    - "config/routes.rb"

Metrics/ClassLength:
  Max: 220
  Exclude:
    - "app/services/importers/xml/*_importer.rb"

Metrics/MethodLength:
  Max: 40
  Exclude:
    - "db/migrate/**/*"

Metrics/AbcSize:
  Max: 40

Metrics/CyclomaticComplexity:
  Max: 10

Layout/LineLength:
  Max: 120
  Exclude:
    - "db/migrate/**/*"
    - "spec/**/*"

RSpec/ExampleLength:
  Max: 20
  Exclude:
    - "spec/services/importers/xml/*_importer_spec.rb"
    - "spec/services/importers/importer_factory_xml_spec.rb"

RSpec/NestedGroups:
  Max: 4

Rails/FilePath:
  Enabled: false
